interface IBanks {
  name: string
  slug: string
  code: string
  ussd: string
  logo: string
}

const banks: IBanks[] = [
  {
    name: 'Access Bank',
    slug: 'access-bank',
    code: '044',
    ussd: '*901#',
    logo: '/img/banks/access-bank.png',
  },
  {
    name: 'Access Bank (Diamond)',
    slug: 'access-bank-diamond',
    code: '063',
    ussd: '*426#',
    logo: '/img/banks/access-bank-diamond.png',
  },
  {
    name: 'ALAT by WEMA',
    slug: 'alat-by-wema',
    code: '035A',
    ussd: '*945*100#',
    logo: '/img/banks/alat-by-wema.png',
  },
  {
    name: 'ASO Savings and Loans',
    slug: 'asosavings',
    code: '401',
    ussd: '',
    logo: '/img/banks/asosavings.png',
  },
  {
    name: 'Bowen Microfinance Bank',
    slug: 'bowen-microfinance-bank',
    code: '50931',
    ussd: '',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'CEMCS Microfinance Bank',
    slug: 'cemcs-microfinance-bank',
    code: '50823',
    ussd: '',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Citibank Nigeria',
    slug: 'citibank-nigeria',
    code: '023',
    ussd: '',
    logo: '/img/banks/citibank-nigeria.png',
  },
  {
    name: 'Ecobank Nigeria',
    slug: 'ecobank-nigeria',
    code: '050',
    ussd: '*326#',
    logo: '/img/banks/ecobank-nigeria.png',
  },
  {
    name: 'Ekondo Microfinance Bank',
    slug: 'ekondo-microfinance-bank',
    code: '562',
    ussd: '*540*178#',
    logo: '/img/banks/ekondo-microfinance-bank.png',
  },
  {
    name: 'Fidelity Bank',
    slug: 'fidelity-bank',
    code: '070',
    ussd: '*770#',
    logo: '/img/banks/fidelity-bank.png',
  },
  {
    name: 'First Bank of Nigeria',
    slug: 'first-bank-of-nigeria',
    code: '011',
    ussd: '*894#',
    logo: '/img/banks/first-bank-of-nigeria.png',
  },
  {
    name: 'First Bank of Nigeria',
    slug: 'first-bank-of-nigeria',
    code: '7',
    ussd: '*894#',
    logo: '/img/banks/first-bank-of-nigeria.png',
  },
  {
    name: 'First City Monument Bank',
    slug: 'first-city-monument-bank',
    code: '214',
    ussd: '*329#',
    logo: '/img/banks/first-city-monument-bank.png',
  },
  {
    name: 'Globus Bank',
    slug: 'globus-bank',
    code: '00103',
    ussd: '*989#',
    logo: '/img/banks/globus-bank.png',
  },
  {
    name: 'Guaranty Trust Bank',
    slug: 'guaranty-trust-bank',
    code: '058',
    ussd: '*737#',
    logo: '/img/banks/guaranty-trust-bank.png',
  },
  {
    name: 'Hasal Microfinance Bank',
    slug: 'hasal-microfinance-bank',
    code: '50383',
    ussd: '*322*127#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Heritage Bank',
    slug: 'heritage-bank',
    code: '030',
    ussd: '*322#',
    logo: '/img/banks/heritage-bank.png',
  },
  {
    name: 'Jaiz Bank',
    slug: 'jaiz-bank',
    code: '301',
    ussd: '*389*301#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Keystone Bank',
    slug: 'keystone-bank',
    code: '082',
    ussd: '*7111#',
    logo: '/img/banks/keystone-bank.png',
  },
  {
    name: 'Kuda Bank',
    slug: 'kuda-bank',
    code: '090267',
    ussd: '',
    logo: '/img/banks/kuda-bank.png',
  },
  {
    name: 'Moniepoint Microfinace Bank',
    slug: 'moniepoint',
    code: '090405',
    ussd: '',
    logo: '/img/banks/moniepoint.png',
  },

  {
    name: 'One Finance',
    slug: 'one-finance',
    code: '565',
    ussd: '*1303#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Opay',
    slug: 'opay',
    code: '100004',
    ussd: '',
    logo: '/img/banks/opay.png',
  },
  {
    name: 'Palmpay',
    slug: 'palmpay',
    code: '100033',
    ussd: '',
    logo: '/img/banks/palmpay.png',
  },

  {
    name: 'Parallex Bank',
    slug: 'parallex-bank',
    code: '526',
    ussd: '*322*318*0#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'PayCom',
    slug: 'paycom',
    code: '100004',
    ussd: '*955#',
    logo: '/img/banks/paycom-bank.png',
  },
  {
    name: 'Polaris Bank',
    slug: 'polaris-bank',
    code: '076',
    ussd: '*833#',
    logo: '/img/banks/polaris-bank.png',
  },
  {
    name: 'Providus Bank',
    slug: 'providus-bank',
    code: '101',
    ussd: '',
    logo: '/img/banks/providus-bank.png',
  },
  {
    name: 'Rubies MFB',
    slug: 'rubies-mfb',
    code: '125',
    ussd: '*7797#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Sparkle Microfinance Bank',
    slug: 'sparkle-microfinance-bank',
    code: '51310',
    ussd: '',
    logo: '/img/banks/sparkle-microfinance-bank.png',
  },
  {
    name: 'Stanbic IBTC Bank',
    slug: 'stanbic-ibtc-bank',
    code: '221',
    ussd: '*909#',
    logo: '/img/banks/stanbic-ibtc-bank.png',
  },
  {
    name: 'Standard Chartered Bank',
    slug: 'standard-chartered-bank',
    code: '068',
    ussd: '',
    logo: '/img/banks/standard-chartered-bank.png',
  },
  {
    name: 'Sterling Bank',
    slug: 'sterling-bank',
    code: '232',
    ussd: '*822#',
    logo: '/img/banks/sterling-bank.png',
  },
  {
    name: 'Suntrust Bank',
    slug: 'suntrust-bank',
    code: '100',
    ussd: '*5230#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'TAJ Bank',
    slug: 'taj-bank',
    code: '302',
    ussd: '*898#',
    logo: '/img/banks/taj-bank.png',
  },
  {
    name: 'TCF MFB',
    slug: 'tcf-mfb',
    code: '51211',
    ussd: '*908#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Titan Trust Bank',
    slug: 'titan-trust-bank',
    code: '102',
    ussd: '*922#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'Union Bank of Nigeria',
    slug: 'union-bank-of-nigeria',
    code: '032',
    ussd: '*826#',
    logo: '/img/banks/union-bank-of-nigeria.png',
  },
  {
    name: 'United Bank For Africa',
    slug: 'united-bank-for-africa',
    code: '033',
    ussd: '*919#',
    logo: '/img/banks/united-bank-for-africa.png',
  },
  {
    name: 'Unity Bank',
    slug: 'unity-bank',
    code: '215',
    ussd: '*7799#',
    logo: '/img/banks/default-image.png',
  },
  {
    name: 'VFD',
    slug: 'vfd',
    code: '090110',
    ussd: '',
    // logo: '/img/banks/v_bank.png',
    logo: '/img/banks/vfd.jpeg',
  },
  {
    name: 'Wema Bank',
    slug: 'wema-bank',
    code: '035',
    ussd: '*945#',
    logo: '/img/banks/wema-bank.png',
  },
  {
    name: 'Zenith Bank',
    slug: 'zenith-bank',
    code: '057',
    ussd: '*966#',
    logo: '/img/banks/zenith-bank.png',
  },
]

export default banks
